Backend/End_Project/End_Project/Models/Size.cs
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace End_Project.Models
{
    public class Size : BaseEntity
    {
        public string Name { get; set; }

        public ICollection<ProductSize> ProductSizes { get; set; }

        [NotMapped]
        public bool IsSelected { get; set; }
    }
}

Backend/End_Project/End_Project/Areas/AdminArea/Controllers/SizeController.cs
using End_Project.Data;
using End_Project.Helpers.Enums;
using End_Project.Models;
using End_Project.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using Size = End_Project.Models.Size;

namespace End_Project.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    [Authorize(Roles = "SuperAdmin,Admin,Member")]
    public class SizeController : Controller
    {
        private readonly AppDbContext _context;
        public SizeController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Size> sizes = await _context.Sizes.Where(m => !m.IsDeleted).ToListAsync();
            return View(sizes);
        }




        [HttpGet]
        [Authorize(Roles = "SuperAdmin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Size size)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }


                bool isExist = await _context.Sizes.AnyAsync(m => m.Name.Trim() == size.Name.Trim());

                if (isExist)
                {
                    ModelState.AddModelError("Name", "Size already exist");
                    return View();
                }


                await _context.Sizes.AddAsync(size);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }


        }



        [HttpGet]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return BadRequest();

            Size size = await _context.Sizes.FindAsync(id);

            if (size == null) return NotFound();

            return View(size);
        }




        [HttpGet]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id == null) return BadRequest();

                Size size = await _context.Sizes.FirstOrDefaultAsync(m => m.Id == id);

                if (size == null) return NotFound();

                return View(size);
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Size size)
        {
            try
            {

                if (!ModelState.IsValid)
                {
                    return View();
                }

                Size dbSize = await _context.Sizes.AsNoTracking().FirstOrDefaultAsync(m => m.Id == id);

                if (dbSize == null) return NotFound();

                if (dbSize.Name.Trim().ToLower() == size.Name.Trim().ToLower())
                {
                    return RedirectToAction(nameof(Index));
                }

                _context.Sizes.Update(size);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }

        }




        [HttpPost]
        [Authorize(Roles = "SuperAdmin,Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            Size size = await GetByIdAsync(id);

            if (size == null) return NotFound();

            _context.Sizes.Remove(size);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }



        private async Task<Size> GetByIdAsync(int id)
        {
            return await _context.Sizes.FindAsync(id);
        }
    }
}

Backend/End_Project/End_Project/Areas/AdminArea/Views/Size/Create.cshtml
@model Size
@{
    ViewData["Title"] = "Create";
}
<div class="container">
    <div class="row my-5">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 style="color:#505668; text-align:center">- Size Create -</h3>

                    <form asp-controller="Size" asp-action="Create" class="forms-sample" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <div>
                                <label for="exampleInputUsername1">Name</label>
                                <textarea class="form-control rounded-0" asp-for="Name" id="Name-area" rows="10"></textarea>
                                <span class="text-danger" asp-validation-for="Name"></span>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary me-2">Create</button>
                        <a asp-controller="Size" asp-action="Index" class="btn btn-primary">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationPartial" />
    <script src="~/ckeditor/ckeditor.js"></script>

    <script>
        CKEDITOR.replace("Name-area")
    </script>
}

Backend/End_Project/End_Project/Areas/AdminArea/Views/Size/Detail.cshtml
@model Size
@{
    ViewData["Title"] = "Detail";
}

@section Link{

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />
}


<div class="container">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 style="text-align:center;color:#505668"> - Size Detail -</h3>
                    <div class="table-responsive pt-3">
                        <table class="table table-bordered table-hover border-dark">
                            <thead style="background:#505668;color:wheat">

                                <tr>
                                    <th>
                                        #
                                    </th>
                                    <th>
                                        Name
                                    </th>
                                </tr>

                            </thead>
                            <tbody>

                                <tr>
                                    <td>
                                        1
                                    </td>
                                    <td>
                                        @Html.Raw(Model.Name)
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a asp-controller="Size" asp-action="Index" class="btn btn-primary">Back</a>
</div>

@section Scripts{

    <script src="https://kit.fontawesome.com/706af225b1.js"></script>
}

Backend/End_Project/End_Project/Areas/AdminArea/Views/Size/Edit.cshtml
@model Size
@{
    ViewData["Title"] = "Edit";
}
<div class="container">
    <div class="row my-5">

        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 style="color:#505668; text-align:center">- Size Edit -</h3>

                    <form asp-controller="Size" asp-action="Edit" class="forms-sample" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <div>
                                <label for="exampleInputUsername1">Name</label>
                                <textarea class="form-control rounded-0" asp-for="Name" id="Name-area" rows="10"></textarea>
                                <span class="text-danger" asp-validation-for="Name"></span>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary me-2">Edit</button>
                        <a asp-controller="Size" asp-action="Index" class="btn btn-primary">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationPartial" />
    <script src="~/ckeditor/ckeditor.js"></script>

    <script>
        CKEDITOR.replace("Name-area")
    </script>
}

Backend/End_Project/End_Project/Areas/AdminArea/Views/Size/Index.cshtml
@model IEnumerable<Size>
@{
    ViewData["Title"] = "Index";
    int count = 1;
}

@section Link{

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />
}


<div class="container">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 style="text-align:center;color:#505668"> - Size Index -</h3>
                    @if (User.IsInRole("SuperAdmin"))
                    {
                        <a type="button" asp-area="AdminArea" asp-controller="Size" asp-action="Create" class="btn btn-success" style="width:65px; height:45px"><i class="fa-solid fa-square-plus" style="font-size:25px;margin:-5px"></i></a>

                    }
                    <div class="table-responsive pt-3">
                        <table class="table table-bordered table-hover border-dark">
                            <thead style="background:#505668;color:wheat">

                                <tr>
                                    <th>
                                        #
                                    </th>
                                    <th>
                                        Name
                                    </th>
                                    <th style="text-align:center">
                                        Settings
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var size in Model)
                                {
                                    <tr>
                                        <td>
                                            @count
                                        </td>
                                        <td>
                                            @Html.Raw(size.Name)
                                        </td>
                                        <td style="text-align:center">
                                            <a asp-action="Detail" asp-route-id="@size.Id" type="button" class="btn btn-info"><i class="fa-solid fa-circle-info"></i></a>
                                            @if (User.IsInRole("SuperAdmin"))
                                            {
                                                <a asp-action="Edit" asp-route-id="@size.Id" type="button" class="btn btn-primary"><i class="fa-solid fa-pen-to-square"></i></a>

                                            }
                                            @if (!User.IsInRole("Member"))
                                            {
                                                <form id="parent-image" style="display: inline-block;" asp-action="Delete" asp-route-id="@size.Id" method="post">
                                                    <button data-id="@size.Id" type="submit" class="btn btn-danger"><i class="fa-solid fa-trash"></i></button>
                                                </form>
                                            }
                                       
                                        </td>
                                    </tr>

                                    count++;
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{

    <script src="https://kit.fontawesome.com/706af225b1.js"></script>
}