Backend/End_Project/End_Project/Models/Banner.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace End_Project.Models
{
    public class Banner : BaseEntity
    {
        public string Image { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Can't be empty")]
        public IFormFile Photo { get; set; }
    }
}

Backend/End_Project/End_Project/Areas/AdminArea/Controllers/BannerController.cs
using End_Project.Data;
using End_Project.Helpers;
using End_Project.Helpers.Enums;
using End_Project.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace End_Project.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    [Authorize(Roles = "SuperAdmin,Admin,Member")]
    public class BannerController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public BannerController(AppDbContext context,IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Banner> banners = await _context.Banners.Where(m => !m.IsDeleted).ToListAsync();
            return View(banners);
        }



        [HttpGet]
        [Authorize(Roles = "SuperAdmin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Banner banner)
        {
            if (!ModelState.IsValid) return View();

            if (!banner.Photo.CheckFileType("image/"))
            {
                ModelState.AddModelError("Photo", "Please choose correct image type");
                return View();
            }

            if (!banner.Photo.CheckFileSize(200))
            {
                ModelState.AddModelError("Photo", "Please choose correct image size");
                return View();
            }

            string fileName = Guid.NewGuid().ToString() + "_" + banner.Photo.FileName;

            string path = Helper.GetFilePath(_env.WebRootPath, "assets/images/banner", fileName);

            using (FileStream stream = new FileStream(path, FileMode.Create))
            {
                await banner.Photo.CopyToAsync(stream);
            }

            banner.Image = fileName;

            await _context.Banners.AddAsync(banner);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }



        [HttpGet]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return BadRequest();

            Banner banner = await _context.Banners.FindAsync(id);

            if (banner == null) return NotFound();

            return View(banner);
        }



        [HttpGet]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id is null) return BadRequest();

                Banner banner = await _context.Banners.FirstOrDefaultAsync(m => m.Id == id);

                if (banner is null) return NotFound();

                return View(banner);

            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Banner banner)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(banner);
                }

                if (!banner.Photo.CheckFileType("image/"))
                {
                    ModelState.AddModelError("Photo", "Please choose correct image type");
                    return View();
                }

                string fileName = Guid.NewGuid().ToString() + "_" + banner.Photo.FileName;

                Banner dbBanner = await _context.Banners.AsNoTracking().FirstOrDefaultAsync(m => m.Id == id);

                if (dbBanner is null) return NotFound();

                if (dbBanner.Photo == banner.Photo)
                {
                    return RedirectToAction(nameof(Index));
                }

                string path = Helper.GetFilePath(_env.WebRootPath, "assets/images/banner", fileName);

                using (FileStream stream = new FileStream(path, FileMode.Create))
                {
                    await banner.Photo.CopyToAsync(stream);
                }

                banner.Image = fileName;

                _context.Banners.Update(banner);

                await _context.SaveChangesAsync();

                string dbPath = Helper.GetFilePath(_env.WebRootPath, "assets/images/banner", dbBanner.Image);

                Helper.DeleteFile(dbPath);

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }
        }


        [Authorize(Roles = "SuperAdmin,Admin")]
        public async Task<IActionResult> Delete(int id)
        {

            Banner banner = await GetByIdAsync(id);

            if (banner == null) return NotFound();

            string path = Helper.GetFilePath(_env.WebRootPath, "assets/images/banner", banner.Image);

            Helper.DeleteFile(path);

            _context.Banners.Remove(banner);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }



        private async Task<Banner> GetByIdAsync(int id)
        {
            return await _context.Banners.FindAsync(id);
        }
    }
}

Backend/End_Project/End_Project/Areas/AdminArea/Views/Banner/Create.cshtml
@model Banner
@{
    ViewData["Title"] = "Create";
}
<div class="container">
    <div class="row my-5">

        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 style="color:#505668; text-align:center">- Banner Create -</h3>

                    <form asp-controller="Banner" asp-action="Create" class="forms-sample" method="post" enctype="multipart/form-data">
                        <div class="form-group">

                            <div>
                                <label for="exampleInputUsername1">Image</label>
                                <input class="form-control" asp-for="Photo">
                                <span class="text-danger" asp-validation-for="Photo"></span>
                            </div>

                            <div>
                                <label for="exampleInputUsername1">Title</label>
                                <textarea class="form-control rounded-0" asp-for="Title" id="Title-area" rows="10"></textarea>
                                <span class="text-danger" asp-validation-for="Title"></span>
                            </div>

                            <div>
                                <label for="exampleInputUsername1">Description</label>
                                <textarea class="form-control rounded-0" asp-for="Description" id="Description-area" rows="10"></textarea>
                                <span class="text-danger" asp-validation-for="Description"></span>
                            </div>

                        </div>

                        <button type="submit" class="btn btn-primary me-2">Create</button>
                        <a asp-controller="Banner" asp-action="Index" class="btn btn-primary">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationPartial" />
    <script src="~/ckeditor/ckeditor.js"></script>

    <script>
        CKEDITOR.replace("Title-area")
        CKEDITOR.replace("Description-area")
    </script>
}

Backend/End_Project/End_Project/Areas/AdminArea/Views/Banner/Detail.cshtml
@model Banner
@{
    ViewData["Title"] = "Detail";
}

@section Link{

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />
}


<div class="container">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 style="text-align:center;color:#505668"> - Banner Detail -</h3>
                    <div class="table-responsive pt-3">
                        <table class="table table-bordered table-hover border-dark">
                            <thead style="background:#505668;color:wheat">

                                <tr>
                                    <th>
                                        #
                                    </th>
                                    <th>
                                        Image
                                    </th>
                                    <th>
                                        Title
                                    </th>
                                    <th>
                                        Description
                                    </th>
                                </tr>

                            </thead>
                            <tbody>

                                <tr>
                                    <td>
                                        1
                                    </td>
                                    <td>
                                        <img style="width:100px; height:100px;border-radius:0 !important " src="~/assets/images/Banner/@Model.Image" alt="slider" />
                                    </td>
                                    <td>
                                        @Html.Raw(Model.Title)
                                    </td>
                                    <td>
                                        @Html.Raw(Model.Description)
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a asp-controller="Banner" asp-action="Index" class="btn btn-primary">Back</a>
</div>

@section Scripts{

    <script src="https://kit.fontawesome.com/706af225b1.js"></script>
}

Backend/End_Project/End_Project/Areas/AdminArea/Views/Banner/Edit.cshtml
@model Banner
@{
    ViewData["Title"] = "Edit";
}
<div class="container">
    <div class="row my-5">

        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 style="color:#505668; text-align:center">- Banner Edit -</h3>

                    <form asp-controller="Banner" asp-action="Edit" class="forms-sample" method="post" enctype="multipart/form-data">
                        <div class="form-group">

                            <div>
                                <label for="exampleInputUsername1">Image</label>
                                <input class="form-control" asp-for="Photo">
                                <span class="text-danger" asp-validation-for="Photo"></span>
                            </div>

                            <div>
                                <label for="exampleInputUsername1">Title</label>
                                <textarea class="form-control rounded-0" asp-for="Title" id="Title-area" rows="10"></textarea>
                                <span class="text-danger" asp-validation-for="Title"></span>
                            </div>

                            <div>
                                <label for="exampleInputUsername1">Description</label>
                                <textarea class="form-control rounded-0" asp-for="Description" id="Description-area" rows="10"></textarea>
                                <span class="text-danger" asp-validation-for="Description"></span>
                            </div>

                        </div>

                        <button type="submit" class="btn btn-primary me-2">Edit</button>
                        <a asp-controller="Banner" asp-action="Index" class="btn btn-primary">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationPartial" />
    <script src="~/ckeditor/ckeditor.js"></script>

    <script>
        CKEDITOR.replace("Title-area")
        CKEDITOR.replace("Description-area")
    </script>
}

Backend/End_Project/End_Project/Areas/AdminArea/Views/Banner/Index.cshtml
@model IEnumerable<Banner>
@{
    ViewData["Title"] = "Index";
    int count = 1;
}

@section Link{

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />
}


<div class="container">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 style="text-align:center;color:#505668"> - Banner Index -</h3>
                    @if (User.IsInRole("SuperAdmin"))
                    {
                        <a type="button" asp-area="AdminArea" asp-controller="Banner" asp-action="Create" class="btn btn-success" style="width:65px; height:45px"><i class="fa-solid fa-square-plus" style="font-size:25px;margin:-5px"></i></a>
                    }
                    <div class="table-responsive pt-3">
                        <table class="table table-bordered table-hover border-dark">
                            <thead style="background:#505668;color:wheat">

                                <tr>
                                    <th>
                                        #
                                    </th>
                                    <th>
                                        Image
                                    </th>
                                    <th>
                                        Title
                                    </th>
                                    <th>
                                        Description
                                    </th>
                                    <th style="text-align:center">
                                        Settings
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var banner in Model)
                                {
                                    <tr>
                                        <td>
                                            @count
                                        </td>
                                        <td>
                                            <img style="width:100px; height:100px;border-radius:0 !important " src="~/assets/images/Banner/@banner.Image" alt="slider" />
                                        </td>
                                        <td>
                                           @Html.Raw(banner.Title)
                                        </td>
                                        <td>
                                           @Html.Raw(banner.Description)
                                        </td>
                                        <td style="text-align:center">
                                            <a asp-action="Detail" asp-route-id="@banner.Id" type="button" class="btn btn-info"><i class="fa-solid fa-circle-info"></i></a>
                                            @if (User.IsInRole("SuperAdmin"))
                                            {
                                                <a asp-action="Edit" asp-route-id="@banner.Id" type="button" class="btn btn-primary"><i class="fa-solid fa-pen-to-square"></i></a>

                                            }
                                            @if (!User.IsInRole("Member"))
                                            {
                                                <form id="parent-image" style="display: inline-block;" asp-action="Delete" asp-route-id="@banner.Id" method="post">
                                                    <button data-id="@banner.Id" type="submit" class="btn btn-danger"><i class="fa-solid fa-trash"></i></button>
                                                </form>
                                            }
                                         
                                        </td>
                                    </tr>

                                    count++;
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{

    <script src="https://kit.fontawesome.com/706af225b1.js"></script>
}